### ISSUE TITLE
Mqtt disconnect issue?

### ISSUE THREAD

**Issue by SanderM2** [klaudiusz223/ComfoAirQ-Homie#4] opened 2022-09-25 10:29 UTC
After running comfoairq-homie I see everything getting posted to my mqtt server, as expected.
But the console screen keeps posting errors like this:

```
2022-09-25 10:25:58,834 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:25:59,836 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:25:59,837 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:25:59,837 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b87d030> None Unknown result code 7
2022-09-25 10:25:59,837 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:00,840 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:00,840 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b725ff0> None Unknown result code 7
2022-09-25 10:26:00,840 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:00,840 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:01,842 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:01,843 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:01,843 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b87d030> None Unknown result code 7
2022-09-25 10:26:01,843 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:02,846 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:02,846 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b725ff0> None Unknown result code 7
2022-09-25 10:26:02,846 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:02,846 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:03,848 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:03,849 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:03,849 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b87d030> None Unknown result code 7
2022-09-25 10:26:03,849 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:04,852 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:04,852 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b725ff0> None Unknown result code 7
2022-09-25 10:26:04,852 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:04,852 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:05,854 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:26:05,855 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:05,855 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b87d030> None Unknown result code 7
2022-09-25 10:26:05,856 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7
2022-09-25 10:26:06,858 - [homie.device_base]  [INFO]  Device MQTT Connected state is False
2022-09-25 10:26:06,858 - [homie.mqtt.paho_mqtt_client]  [WARNING]  MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7f9d0b725ff0> None Unknown result code 7
2022-09-25 10:26:06,858 - [homie.mqtt.mqtt_base]  [WARNING]  MQTT On Disconnect: Result Code 7

```

I have no idea why it's constantly disconnecting so I hope you can help?

**Comment by SanderM2** [comment] 2022-09-25 10:39
My mqtt server logs read:

2022-09-25 12:26:03: Client comfoair already connected, closing old connection.

So it looks like it's making multiple connections.

Now, I do see strange things like this when starting :

```
# PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python comfoairq-homie -c config.yml 
2022-09-25 10:36:40,144 - [comfoairq_homie.__main__]  [INFO]  Starting ComfoAirQ-Homie version 0.6.2
2022-09-25 10:36:40,144 - [comfoairq_homie.__main__]  [INFO]  Starting ComfoAirQ-Homie version 0.6.2
2022-09-25 10:36:40,144 - [comfoairq_homie.__main__]  [INFO]  Waiting... Stop with CTRL+C
2022-09-25 10:36:40,144 - [comfoairq_homie.__main__]  [INFO]  Waiting... Stop with CTRL+C
2022-09-25 10:36:40,145 - [homie.mqtt.homie_mqtt_client]  [INFO]  Using new MQTT client, number of instances 0
2022-09-25 10:36:40,145 - [homie.mqtt.mqtt_base]  [INFO]  MQTT set will homie/zehnderq600/$state, topic lost
2022-09-25 10:36:40,146 - [homie.mqtt.paho_mqtt_client]  [INFO]  Starting MQTT publish thread
2022-09-25 10:36:40,146 - [homie.mqtt.paho_mqtt_client]  [INFO]  Starting Asyincio looping forever
2022-09-25 10:36:40,147 - [homie.device_base]  [INFO]  Device Start ZehnderQ600
2022-09-25 10:36:40,147 - [homie.device_base]  [INFO]  Device MQTT Connected state is True
2022-09-25 10:36:40,150 - [homie.mqtt.homie_mqtt_client]  [INFO]  Using new MQTT client, number of instances 1
2022-09-25 10:36:40,150 - [homie.mqtt.mqtt_base]  [INFO]  MQTT set will homie/zehnderq600gateway/$state, topic lost
2022-09-25 10:36:40,153 - [homie.mqtt.paho_mqtt_client]  [INFO]  Starting MQTT publish thread
2022-09-25 10:36:40,153 - [homie.mqtt.paho_mqtt_client]  [INFO]  Starting Asyincio looping forever
```


Every log entry is double so it looks like it's running two times in parallel while I only start it once?


PS: I did have to add "PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python" because I get this error without it:

```
Traceback (most recent call last):
  File "/usr/local/bin/comfoairq-homie", line 5, in <module>
    from comfoairq_homie.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/comfoairq_homie/__main__.py", line 11, in <module>
    from .comfoairq_homie import ComfoAirQ_Homie
  File "/usr/local/lib/python3.10/dist-packages/comfoairq_homie/comfoairq_homie.py", line 4, in <module>
    from .homie_device.device_comfoairq         import  Device_ComfoAirQ
  File "/usr/local/lib/python3.10/dist-packages/comfoairq_homie/homie_device/device_comfoairq.py", line 5, in <module>
    from pycomfoconnect.const import *
  File "/usr/local/lib/python3.10/dist-packages/pycomfoconnect/__init__.py", line 11, in <module>
    from .comfoconnect import *
  File "/usr/local/lib/python3.10/dist-packages/pycomfoconnect/comfoconnect.py", line 7, in <module>
    from .bridge import Bridge
  File "/usr/local/lib/python3.10/dist-packages/pycomfoconnect/bridge.py", line 5, in <module>
    from .message import *
  File "/usr/local/lib/python3.10/dist-packages/pycomfoconnect/message.py", line 4, in <module>
    from .zehnder_pb2 import *
  File "/usr/local/lib/python3.10/dist-packages/pycomfoconnect/zehnder_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by SanderM2** [comment] 2022-09-25 10:41
I just tried "pip3 install protobuf==3.20.*" and tried again without 'PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python'. Still the same issue.

For some reason it looks like it's starting twice, parallel, while I only start it once. 

I have no idea why :(

**Comment by klaudiusz223** [comment] 2022-09-25 11:30
Hi @SanderM2 
What are Your settings in `comfoairq_homie.yml`?
comfoairq-homie creates two homie devices at start. Each of the homie device requires mqtt connection
They can share one mqtt connection but they can also use 2 different connections.
Configuration for this is in the file `comfoairq_homie.yml `(mqtt part)

This 2 settings are crucial
```
  MQTT_CLIENT_ID: null 
  MQTT_SHARE_CLIENT: False
```

set `MQTT_CLIENT_ID` to **null** if You do not want to share the connection
or set `MQTT_SHARE_CLIENT `= **True** if You want to set the client_id
Or You can also try to change settings in mqtt server .
I use 
```
  MQTT_CLIENT_ID: null 
  MQTT_SHARE_CLIENT: False
```
So it's probably preferable :-)

Let me know if this helps

I have also the issue with doble log entries but i think it's not because of Comfoairq starts twice. maybe  I will look into this issue in the future if I have time.

Regarding `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION `issue.
Preferably downgrade protobuf to 3.20.x as I did the same recently.
It's the issue of dependecies of pycomfoconnect (https://github.com/michaelarnauts/comfoconnect/).

**Comment by SanderM2** [comment] 2022-09-25 12:08
The problem turns out that I entered a string for "MQTT_CLIENT_ID" while it had to be "null". After changing it to "null" everything is working.

I do notice that when starting comfoairq-homie it first posts 0 values before posting the correct values. 
Like this:

```
homie/zehnderq600/sensors/temperature-outdoor 0.0
homie/zehnderq600/sensors/temperature-supply 0.0
homie/zehnderq600/sensors/temperature-extract 0.0
homie/zehnderq600/sensors/temperature-exhaust 0.0
homie/zehnderq600/sensors/temperature-supply 19.9
homie/zehnderq600/sensors/temperature-extract 22.4
homie/zehnderq600/sensors/temperature-outdoor 16.7
homie/zehnderq600/sensors/temperature-exhaust 21.1
homie/zehnderq600/sensors/temperature-outdoor 16.6
homie/zehnderq600/sensors/temperature-exhaust 21.0
```



I'm integrating this with home assistant and because of the fact that it first posts a 0 it's showing false values in the charts.
Can this behaviour easily be changed?

**Comment by klaudiusz223** [comment] 2022-09-25 12:18
0-values are a known issue. https://github.com/michaelarnauts/comfoconnect/issues/44.
Will theoretically be resolved by Zehnder when the next firmware version is released. 
I hope this will happen soon because the beta version is already available. I'm unlikely to fix it on the ComfoAirQ-Homie side
Klaudiusz

**Comment by klaudiusz223** [comment] 2022-09-25 12:29
> The problem turns out that I entered a string for "MQTT_CLIENT_ID" while it had to be "null". After changing it to "null" everything is working.

The issue is resolved

**Closed as completed** 2022-09-25 12:29 UTC
